name: daylight
description: Get the sunset and sunrise times for a geolocation without having to access any api.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  intl:
  angles: 1.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: